In [1]:
import pandas as pd

train_df= pd.read_csv('/home/cc1/Documents/Code/AIO-IDS/data/out_cicids2017/train_MachineLearningCVE.csv')

In [2]:
train_df.Label.value_counts()

Label
0     1818477
4      184858
10     127144
2      102422
3        8234
7        6350
11       4717
6        4637
5        4399
1        1573
12       1206
14        522
9          29
13         17
8           9
Name: count, dtype: int64

In [3]:
from sklearn.preprocessing import QuantileTransformer

In [4]:
train_df=train_df.drop(columns=['Unnamed: 0'])
X = train_df.drop(columns=['Label'])
y = train_df['Label']

In [5]:
type(X)

pandas.core.frame.DataFrame

In [6]:
X = X.iloc[:, :9]

In [7]:
type(X)

pandas.core.frame.DataFrame

In [8]:
scaler = QuantileTransformer() 
X_scale = scaler.fit_transform(X)

In [9]:
X_df = pd.DataFrame(X_scale, columns=X.columns, index=X.index)

In [10]:
X_df

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean
0,0.183183,0.540779,0.435936,0.574074,0.577578,0.453954,0.488488,0.758258,0.537037
1,0.009009,0.229217,0.000000,0.297297,0.221221,0.296296,0.257758,0.575576,0.264264
2,0.684184,0.632015,0.888388,0.773273,0.945617,0.718225,0.973807,0.000000,0.958320
3,0.463964,0.967996,0.933433,0.928428,0.842144,0.785784,0.880881,0.000000,0.452770
4,0.463964,0.764652,0.662162,0.297297,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
2264589,0.684184,0.033534,0.435936,0.000000,0.269770,0.000000,0.257758,0.575576,0.264264
2264590,0.463964,0.516914,0.000000,0.297297,0.221221,0.296296,0.257758,0.575576,0.264264
2264591,0.684184,0.625951,0.783283,0.773273,0.866778,0.812456,0.918418,0.000000,0.928970
2264592,0.183183,0.571852,0.435936,0.574074,0.484484,0.673173,0.373874,0.665165,0.432933
2264593,0.183183,0.535251,0.000000,0.297297,0.419419,0.452452,0.662663,0.917417,0.732733

In [11]:
X_df = X_df.apply(
    lambda x: (x*255))

In [12]:
X_df

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean
0,46.711712,137.898591,111.163664,146.388889,147.282282,115.758258,124.564565,193.355856,136.944444
1,2.297297,58.450240,0.000000,75.810811,56.411411,75.555556,65.728228,146.771772,67.387387
2,174.466967,161.163798,226.539039,197.184685,241.132408,183.147482,248.320821,0.000000,244.371671
3,118.310811,246.838967,238.025526,236.749249,214.746709,200.374999,224.624625,0.000000,115.456272
4,118.310811,194.986162,168.851351,75.810811,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
2264589,174.466967,8.551051,111.163664,0.000000,68.791291,0.000000,65.728228,146.771772,67.387387
2264590,118.310811,131.813182,0.000000,75.810811,56.411411,75.555556,65.728228,146.771772,67.387387
2264591,174.466967,159.617460,199.737237,197.184685,221.028333,207.176246,234.196697,0.000000,236.887334
2264592,46.711712,145.822275,111.163664,146.388889,123.543544,171.659159,95.337838,169.617117,110.397898
2264593,46.711712,136.489076,0.000000,75.810811,106.951952,115.375375,168.978979,233.941441,186.846847

In [13]:
df = pd.concat([X_df, y], axis=1)
df

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Label
0,46.711712,137.898591,111.163664,146.388889,147.282282,115.758258,124.564565,193.355856,136.944444,0
1,2.297297,58.450240,0.000000,75.810811,56.411411,75.555556,65.728228,146.771772,67.387387,0
2,174.466967,161.163798,226.539039,197.184685,241.132408,183.147482,248.320821,0.000000,244.371671,0
3,118.310811,246.838967,238.025526,236.749249,214.746709,200.374999,224.624625,0.000000,115.456272,0
4,118.310811,194.986162,168.851351,75.810811,0.000000,0.000000,0.000000,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...
2264589,174.466967,8.551051,111.163664,0.000000,68.791291,0.000000,65.728228,146.771772,67.387387,0
2264590,118.310811,131.813182,0.000000,75.810811,56.411411,75.555556,65.728228,146.771772,67.387387,0
2264591,174.466967,159.617460,199.737237,197.184685,221.028333,207.176246,234.196697,0.000000,236.887334,0
2264592,46.711712,145.822275,111.163664,146.388889,123.543544,171.659159,95.337838,169.617117,110.397898,0
2264593,46.711712,136.489076,0.000000,75.810811,106.951952,115.375375,168.978979,233.941441,186.846847,0

In [15]:
df0=df[df['Label']==0].drop(['Label'],axis=1)
df1=df[df['Label']==1].drop(['Label'],axis=1)
df2=df[df['Label']==2].drop(['Label'],axis=1)
df3=df[df['Label']==3].drop(['Label'],axis=1)
df4=df[df['Label']==4].drop(['Label'],axis=1)
df5=df[df['Label']==5].drop(['Label'],axis=1)
df6=df[df['Label']==6].drop(['Label'],axis=1)
df7=df[df['Label']==7].drop(['Label'],axis=1)
df8=df[df['Label']==8].drop(['Label'],axis=1)
df9=df[df['Label']==9].drop(['Label'],axis=1)
df10=df[df['Label']==10].drop(['Label'],axis=1)
df11=df[df['Label']==11].drop(['Label'],axis=1)
df12=df[df['Label']==12].drop(['Label'],axis=1)
df13=df[df['Label']==13].drop(['Label'],axis=1)
df14=df[df['Label']==14].drop(['Label'],axis=1)

In [16]:
df0

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean
0,46.711712,137.898591,111.163664,146.388889,147.282282,115.758258,124.564565,193.355856,136.944444
1,2.297297,58.450240,0.000000,75.810811,56.411411,75.555556,65.728228,146.771772,67.387387
2,174.466967,161.163798,226.539039,197.184685,241.132408,183.147482,248.320821,0.000000,244.371671
3,118.310811,246.838967,238.025526,236.749249,214.746709,200.374999,224.624625,0.000000,115.456272
4,118.310811,194.986162,168.851351,75.810811,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
2264589,174.466967,8.551051,111.163664,0.000000,68.791291,0.000000,65.728228,146.771772,67.387387
2264590,118.310811,131.813182,0.000000,75.810811,56.411411,75.555556,65.728228,146.771772,67.387387
2264591,174.466967,159.617460,199.737237,197.184685,221.028333,207.176246,234.196697,0.000000,236.887334
2264592,46.711712,145.822275,111.163664,146.388889,123.543544,171.659159,95.337838,169.617117,110.397898
2264593,46.711712,136.489076,0.000000,75.810811,106.951952,115.375375,168.978979,233.941441,186.846847

In [23]:
!pip install networkx

Collecting networkx
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Installing collected packages: networkx
Successfully installed networkx-3.2.1

In [24]:
import os
import numpy as np
from PIL import Image

In [28]:
import os
import numpy as np
from PIL import Image

def save_images_from_df(df, folder_name):
    count = 0
    ims = []

    image_path = f"/home/cc1/Documents/Code/AIO-IDS/data/image_cicids2017/train/{folder_name}/"
    os.makedirs(image_path, exist_ok=True)

    for i in range(len(df)):  
        count += 1
        if count <= 27: 
            im = df.iloc[i].values
            ims = np.append(ims, im)
        else:
            ims = np.array(ims).reshape(9, 9, 3)
            array = np.array(ims, dtype=np.uint8)
            new_image = Image.fromarray(array)
            new_image.save(image_path + str(i) + '.png')
            count = 0
            ims = []

for idx in range(15):  
    df_name = f"df{idx}" 
    
    df = globals().get(df_name)
    
    if df is not None:  # Kiểm tra xem DataFrame có tồn tại không
        folder_name = str(idx)  # Tạo tên thư mục tương ứng
        save_images_from_df(df, folder_name)  # Gọi hàm lưu ảnh
    else:
        print(f"DataFrame {df_name} không tồn tại.")

In [29]:
import cv2
def get_224(folder,dstdir):
    imgfilepaths=[]
    for root,dirs,imgs in os.walk(folder):
        for thisimg in imgs:
            thisimg_path=os.path.join(root,thisimg)
            imgfilepaths.append(thisimg_path)
    for thisimg_path in imgfilepaths:
        dir_name,filename=os.path.split(thisimg_path)
        dir_name=dir_name.replace(folder,dstdir)
        new_file_path=os.path.join(dir_name,filename)
        if not os.path.exists(dir_name):
            os.makedirs(dir_name)
        img=cv2.imread(thisimg_path)
        img=cv2.resize(img,(224,224))
        cv2.imwrite(new_file_path,img)
    print('Finish resizing'.format(folder=folder))

In [30]:
DATA_DIR_224='/home/cc1/Documents/Code/AIO-IDS/data/image_cicids2017/train_224'
DATA_DIR_9 = '/home/cc1/Documents/Code/AIO-IDS/data/image_cicids2017/train'
get_224(folder=DATA_DIR_9,dstdir=DATA_DIR_224)

Finish resizing

In [26]:
count=0
ims = []

image_path = "/home/cc1/Documents/Code/AIO-IDS/data/image_cicids2017/train/0/"
os.makedirs(image_path, exist_ok=True)

for i in range(0, len(df0)):  
    count=count+1
    if count<=27: 
        im=df0.iloc[i].values
        ims=np.append(ims,im)
    else:
        ims=np.array(ims).reshape(9,9,3)
        array = np.array(ims, dtype=np.uint8)
        new_image = Image.fromarray(array)
        new_image.save(image_path+str(i)+'.png')
        count=0
        ims = []